name: pet_shop_app
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.2.0
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
  json_annotation: ^4.8.0
  dio: ^5.0.0
  flutter_screenutil: ^5.9.3
  go_router: ^14.0.0
  intl: ^0.20.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
  flutter_lints: ^5.0.0


flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/
