name: pet_shop_app
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"


dependencies:
  # Core Flutter SDK
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.2.0

  # Networking
  dio: ^5.0.0

  # Routing
  go_router: ^14.0.0

  # Localization
  intl: ^0.20.2

  # UI Utilities
  flutter_screenutil: ^5.9.3

  # Code Generation
  json_serializable: ^6.8.0
  json_annotation: ^4.8.0
  build_runner: ^2.4.0
  envied: ^1.0.0

  # Social Authentication
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.2

  # Local Storage
  shared_preferences: ^2.2.2



dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mocktail: ^1.0.0

  # Linting & Analysis
  very_good_analysis: ^8.0.0
  flutter_lints: ^5.0.0

  # Environment
  envied_generator: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/

